export const siteConfig = {
  name: "CCTV Name",
  url: "https://www.cctv.name",
  ogImage: "https://www.cctv.name/og.svg",
  description:
    "Expert CCTV and surveillance solutions — reviews, installation guides, and security tips for your home and business.",
  keywords: [
    "CCTV",
    "cctv camera",
    "surveillance",
    "security cameras",
    "security camera",
    "home security",
    "business surveillance",
    "security systems",
    "video surveillance",
    "camera installation",
  ],
  links: {
    youtube: "https://youtube.com/@cctvname",
    github: "https://github.com/cctvname",
  },
  affiliate: {
    amazon: {
      tag: "",
      baseUrl: "https://www.amazon.com",
    },
  },
  author: {
    name: "CCTV Name Team",
  },
  localeMap: {
    en: "en-US",
    es: "es-ES",
    fr: "fr-FR",
    de: "de-DE",
    hi: "hi-IN",
    ar: "ar-SA",
    zh: "zh-CN",
    ru: "ru-RU",
    pt: "pt-BR",
    ja: "ja-JP",
    ko: "ko-KR",
    it: "it-IT",
    nl: "nl-NL",
    pl: "pl-PL",
    tr: "tr-TR",
    bn: "bn-BD",
    ur: "ur-PK",
    id: "id-ID",
    vi: "vi-VN",
    th: "th-TH",
    uk: "uk-UA",
  } as Record<string, string>,
  themeColor: {
    light: "#ffffff",
    dark: "#09090b",
  },
}
